apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
