apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Release.Namespace }}'
  name: "briefer-jupyter-service"
spec:
  selector:
    app.kubernetes.io/name: "briefer"
    app.kubernetes.io/component: "jupyter"
  ports:
  - port: 8888
    targetPort: jupyter-port
