apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
