{{- if .Values.ai.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ai
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: ai
spec:
  selector:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: ai
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
{{- end }}
