{{- if .Values.ai.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
data:
  aiApiUsername: '{{ .Values.ai.secrets.aiApiUsername | b64enc }}'
  aiApiPassword: '{{ .Values.ai.secrets.aiApiPassword | b64enc }}'
  openAiApiKey: '{{ .Values.ai.secrets.openAiApiKey | b64enc }}'
{{- end }}
