{{- if .Values.enableLocalPostgres }}
apiVersion: v1
kind: Service
metadata:
  namespace: briefer
  name: {{ .Values.api.env.postgresHostname }}
spec:
  selector:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: postgres
  ports:
  - protocol: TCP
    port: {{.Values.api.env.postgresPort}}
    targetPort: postgres-port
{{- end }}
